// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/feed-cards/VarianteA.tsx": () => import("../components/mockups/feed-cards/VarianteA.tsx"),
  "./components/mockups/feed-cards/VarianteB.tsx": () => import("../components/mockups/feed-cards/VarianteB.tsx"),
  "./components/mockups/feed-redesign/CalmShortlist.tsx": () => import("../components/mockups/feed-redesign/CalmShortlist.tsx"),
  "./components/mockups/feed-redesign/Curated.tsx": () => import("../components/mockups/feed-redesign/Curated.tsx"),
  "./components/mockups/feed-redesign/CuratedEditorial.tsx": () => import("../components/mockups/feed-redesign/CuratedEditorial.tsx"),
  "./components/mockups/feed-redesign/Current.tsx": () => import("../components/mockups/feed-redesign/Current.tsx"),
  "./components/mockups/feed-redesign/ShortlistGuided.tsx": () => import("../components/mockups/feed-redesign/ShortlistGuided.tsx"),
  "./components/mockups/feed-redesign/Timeline.tsx": () => import("../components/mockups/feed-redesign/Timeline.tsx"),
  "./components/mockups/job-detail/DecisionFirst.tsx": () => import("../components/mockups/job-detail/DecisionFirst.tsx"),
  "./components/mockups/job-details-reconstruction/JobDetails.tsx": () => import("../components/mockups/job-details-reconstruction/JobDetails.tsx"),
  "./components/mockups/job-details-reconstruction/MatchingProofVariant.tsx": () => import("../components/mockups/job-details-reconstruction/MatchingProofVariant.tsx"),
  "./components/mockups/job-matching-reconstruction/JobMatchingVariant.tsx": () => import("../components/mockups/job-matching-reconstruction/JobMatchingVariant.tsx"),
  "./components/mockups/jobagogo-flow/JobagogoFlow.tsx": () => import("../components/mockups/jobagogo-flow/JobagogoFlow.tsx"),
  "./components/mockups/jobseek-homepage/Homepage.tsx": () => import("../components/mockups/jobseek-homepage/Homepage.tsx"),
  "./components/mockups/search-results-reconstruction/SearchResults.tsx": () => import("../components/mockups/search-results-reconstruction/SearchResults.tsx"),
  "./components/mockups/splash-screens/JobagogoMobbin.tsx": () => import("../components/mockups/splash-screens/JobagogoMobbin.tsx"),
  "./components/mockups/splash-screens/JobagogoMobbinAmber.tsx": () => import("../components/mockups/splash-screens/JobagogoMobbinAmber.tsx"),
  "./components/mockups/uploaded-design/UploadedDesign.tsx": () => import("../components/mockups/uploaded-design/UploadedDesign.tsx"),
  "./components/mockups/uploaded-design/UploadedDesign2.tsx": () => import("../components/mockups/uploaded-design/UploadedDesign2.tsx")
};
